CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
                                                       "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
    );

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetRoles" (
                                      "Id" text NOT NULL,
                                      "Name" character varying(256),
                                      "NormalizedName" character varying(256),
                                      "ConcurrencyStamp" text,
                                      CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetUsers" (
                                      "Id" text NOT NULL,
                                      "Name" text NOT NULL,
                                      "PlanId" character varying(50) NOT NULL DEFAULT 'free',
                                      "UserName" character varying(256),
                                      "NormalizedUserName" character varying(256),
                                      "Email" character varying(256),
                                      "NormalizedEmail" character varying(256),
                                      "EmailConfirmed" boolean NOT NULL,
                                      "PasswordHash" text,
                                      "SecurityStamp" text,
                                      "ConcurrencyStamp" text,
                                      "PhoneNumber" text,
                                      "PhoneNumberConfirmed" boolean NOT NULL,
                                      "TwoFactorEnabled" boolean NOT NULL,
                                      "LockoutEnd" timestamp with time zone,
                                      "LockoutEnabled" boolean NOT NULL,
                                      "AccessFailedCount" integer NOT NULL,
                                      CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."Permissions" (
                                      "Id" uuid NOT NULL,
                                      "Name" character varying(100) NOT NULL,
                                      "Description" text,
                                      CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."Plans" (
                                "Id" character varying(50) NOT NULL,
                                "Name" character varying(100) NOT NULL,
                                "IsActive" boolean NOT NULL,
                                CONSTRAINT "PK_Plans" PRIMARY KEY ("Id")
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetRoleClaims" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "RoleId" text NOT NULL,
                                           "ClaimType" text,
                                           "ClaimValue" text,
                                           CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
                                           CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetUserClaims" (
                                           "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                                           "UserId" text NOT NULL,
                                           "ClaimType" text,
                                           "ClaimValue" text,
                                           CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
                                           CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetUserLogins" (
                                           "LoginProvider" text NOT NULL,
                                           "ProviderKey" text NOT NULL,
                                           "ProviderDisplayName" text,
                                           "UserId" text NOT NULL,
                                           CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
                                           CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetUserRoles" (
                                          "UserId" text NOT NULL,
                                          "RoleId" text NOT NULL,
                                          CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
                                          CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles" ("Id") ON DELETE CASCADE,
                                          CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."AspNetUserTokens" (
                                           "UserId" text NOT NULL,
                                           "LoginProvider" text NOT NULL,
                                           "Name" text NOT NULL,
                                           "Value" text,
                                           CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
                                           CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE TABLE public."PlanPermissions" (
                                          "PlanId" character varying(50) NOT NULL,
                                          "PermissionId" uuid NOT NULL,
                                          CONSTRAINT "PK_PlanPermissions" PRIMARY KEY ("PlanId", "PermissionId"),
                                          CONSTRAINT "FK_PlanPermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES public."Permissions" ("Id") ON DELETE CASCADE,
                                          CONSTRAINT "FK_PlanPermissions_Plans_PlanId" FOREIGN KEY ("PlanId") REFERENCES public."Plans" ("Id") ON DELETE CASCADE
);
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" ("RoleId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" ("NormalizedName");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" ("UserId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" ("RoleId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "EmailIndex" ON public."AspNetUsers" ("NormalizedEmail");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" ("NormalizedUserName");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE UNIQUE INDEX "IX_Permissions_Name" ON public."Permissions" ("Name");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
CREATE INDEX "IX_PlanPermissions_PermissionId" ON public."PlanPermissions" ("PermissionId");
END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260412174847_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260412174847_Initial', '10.0.5');
END IF;
END $EF$;
COMMIT;

